language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0

jdk:
  - openjdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

env:
  global:
    - COURSIER_PROGRESS=0

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 test

